apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: data

resources:
  - postgresql-deployment.yaml
  - backend-deployment.yaml
  - frontend-deployment.yaml
  - configmap.yaml
  - secret.yaml
  - servicemonitor.yaml

commonLabels:
  tenant: data
  managed-by: terraform

